name: PHPUnit

on: [pull_request]

jobs:
  validate-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: magento_test
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: magento
          MYSQL_PASSWORD: p@ssw0rd1
          MYSQL_ROOT_PASSWORD: p@ssw0rd1
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.3"
          extensions: curl, dom, intl, json, openssl
          coverage: xdebug

      - name: Verify PHP Installation
        run: php -v

      - name: Composer downgrade to version 1
        id: composer-downgrade
        run: composer self-update --1

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Setup cache
        uses: pat-s/always-upload-cache@v1.1.4
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install & Build Magento
        id: build-magento
        run: bash bin/install-mg2.sh

      - name: Install MP Plugin
        id: install-plugin
        run: mv src/* magento2/app/code

      - name: Run Unit Test
        id: unit-test
        run: magento2/vendor/phpunit/phpunit/phpunit --colors=always --whitelist magento2/app/code/MercadoPago/Core --coverage-clover clover.xml --coverage-text magento2/app/code/MercadoPago/Test

      - name: Repository Minimum Test Coverage
        id: repository-coverage
        run: php magento2/app/code/MercadoPago/Test/coverage-checker.php clover.xml 80

      - name: Composer upgrade to version 2
        id: composer-upgrade
        run: composer self-update --2

      - name: Install php-code-coverage-verifier
        id: install-php-code-coverage-verifier
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        run: cd magento2 && composer require tomzx/php-code-coverage-verifier:dev-master --no-plugins --with-all-dependencies

      - name: Composer downgrade to version 1
        id: pr-coverage-composer-downgrade
        run: composer self-update --1

      - name: Generate git diff
        id: git-diff
        run: git diff --color --no-prefix > pr-coverage.patch

      - name: Pull Request Minimum Coverage
        id: pull-request-coverage
        run: php magento2/vendor/bin/php-code-coverage-verifier verify clover.xml pr-coverage.patch



